swagger: '2.0'
info:
  version: '0.0.1'
  title: RBKmoney Dark Resource API
  description: >

    RBKmoney Dark Resource API служит для управления секретных вызовов.

  termsOfService: http://rbk.money/
  contact:
    name: RBKmoney support team
    email: support@rbk.money
    url: https://rbk.money
host: api.rbk.money
basePath: /dapi/v0
schemes:
  - https
consumes:
  - application/json; charset=utf-8
produces:
  - application/json; charset=utf-8
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
    description: >
      Для аутентификации вызовов мы используем [JWT](https://jwt.io).
      Cоответствующий ключ передается в заголовке.

      ```shell
       Authorization: Bearer {TOKENIZATION|PRIVATE_JWT}
      ```

security:
  - bearer: []

responses:
  NotFound:
    description: Заданный ресурс не найден
    schema:
      $ref: '#/definitions/GeneralError'
  QuestionaryNotFound:
    description: Заданный ресурс не найден
    schema:
      $ref: '#/definitions/GeneralError'
  Unauthorized:
    description: Ошибка авторизации
  ExternalIDConflict:
    description: Переданное значение `externalID` уже использовалось вами ранее с другими параметрами запроса
    schema:
      $ref: '#/definitions/ExternalIDConflictError'
  DefaultLogicError:
    description: Неверные данные
    schema:
      $ref: '#/definitions/DefaultLogicError'

parameters:
  requestID:
    name: X-Request-ID
    in: header
    description: Уникальный идентификатор запроса к системе
    required: true
    type: string
    maxLength: 32
    minLength: 1
  shopID:
    name: shopID
    in: path
    description: Идентификатор магазина
    required: true
    type: string
    maxLength: 40
    minLength: 1
  claimID:
    name: claimID
    in: path
    description: Идентификатор заявки
    required: true
    type: integer
    format: int64
  claimRevision:
    name: claimRevision
    in: query
    description: Версия заявки
    required: true
    type: integer
    format: int32
  paymentID:
    name: paymentID
    in: path
    description: Идентификатор платежа в рамках инвойса
    required: true
    type: string
    maxLength: 40
    minLength: 1
  refundID:
    name: refundID
    in: path
    description: Идентификатор возврата в рамках платежа
    required: true
    type: string
    maxLength: 40
    minLength: 1
  customerID:
    name: customerID
    in: path
    description: Идентификатор кастомера
    required: true
    type: string
    maxLength: 40
    minLength: 1
  payoutID:
    name: payoutID
    in: path
    description: Идентификатор вывода
    required: true
    type: string
    maxLength: 40
    minLength: 1
  invoiceID:
    name: invoiceID
    in: path
    description: Идентификатор инвойса
    required: true
    type: string
    maxLength: 40
    minLength: 1
  fromTime:
    name: fromTime
    in: query
    description: Начало временного отрезка
    required: true
    type: string
    format: date-time
  toTime:
    name: toTime
    in: query
    description: Конец временного отрезка
    required: true
    type: string
    format: date-time
  limit:
    name: limit
    in: query
    description: Лимит выборки
    required: true
    type: integer
    format: int32
    minimum: 1
    maximum: 1000
  deadline:
    name: X-Request-Deadline
    in: header
    description: Максимальное время обработки запроса
    required: false
    type: string
    maxLength: 40
    minLength: 1
  fileID:
    name: fileID
    in: path
    description: Идентификатор файла
    required: true
    type: string
    maxLength: 40
    minLength: 1

tags:
  - name: Search
    x-displayName: Управление поиском
    description: ""

  - name: Questionary
    x-displayName: Управление анкетами
    description: ""

  - name: Claims
    x-displayName: Заявки
    description: >
      Некоторая область данных может быть изменена только после премодерации на
      стороне платформы. Например, создание и активация новых магазинов,
      изменение финансовых данных вашего участника и т.п. требуют ручной
      проверки сотрудниками RBKmoney. Попытка изменить такие данные приводит к
      автоматическому созданию заявки на изменение данных. До тех пор, пока
      заявка не одобрена, вы можете добавлять изменения. После одобрения они
      будут применены к набору данных. В случае отказа по заявке данные
      останутся в неизменном состоянии. Ближайшим аналогом заявок можно
      представить Pull Request в распределенных системах контроля версий.

  - name: Files
    x-displayName: Управление файлами
    description: >
      Получение ссылки на загрузку, получение ссылки на скачивание, информация о файле.
